- name: add apt key for nodesource
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: install nodejs
  apt:
    name: ["nodejs", "npm"]
    state: latest

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy index test page
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: Executing node
  shell: |
    pm2 start ~/web/index.js -f