version: 2.1
destroy_environment:
  steps:
    - run:
        name: Destroy environment
        # ${CIRCLE_WORKFLOW_ID} is a Built-in environment variable
        when: on_fail
        command: |
          aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
                    --template-file cloudformation/infra.yml \
                    --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                    --profile default
workflows:
  pipleine:
    jobs:
      - create_infrastructure
